version: 2.0

references:
  default_container: &default_container
    docker:
      - image: circleci/node:14
  restore_repo: &restore_repo
    restore_cache:
      key: npm-cache-{{ checksum "package-lock.json" }}

jobs:
  checkout_and_install:
    <<: *default_container
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint:
    <<: *default_container
    steps:
      - checkout
      - *restore_repo
      - run: npm run lint
  node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node11:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node13:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node14:
    <<: *default_container
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test
  node15:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - *restore_repo
      - run: npm run unit-test

workflows:
  version: 2
  lint_and_test_node_versions:
    jobs:
      - checkout_and_install
      - lint:
          requires:
            - checkout_and_install
      - node8:
          requires:
            - checkout_and_install
      - node9:
          requires:
            - checkout_and_install
      - node10:
          requires:
            - checkout_and_install
      - node11:
          requires:
            - checkout_and_install
      - node12:
          requires:
            - checkout_and_install
      - node13:
          requires:
            - checkout_and_install
      - node14:
          requires:
            - checkout_and_install
      - node15:
          requires:
            - checkout_and_install
